var annotated_dup =
[
    [ "Assimp", "namespace_assimp.html", "namespace_assimp" ],
    [ "_IEEEDouble", "union___i_e_e_e_double.html", "union___i_e_e_e_double" ],
    [ "_IEEESingle", "union___i_e_e_e_single.html", "union___i_e_e_e_single" ],
    [ "aiAABB", "structai_a_a_b_b.html", "structai_a_a_b_b" ],
    [ "aiAnimation", "structai_animation.html", "structai_animation" ],
    [ "aiAnimMesh", "structai_anim_mesh.html", "structai_anim_mesh" ],
    [ "aiBone", "structai_bone.html", "structai_bone" ],
    [ "aiCamera", "structai_camera.html", "structai_camera" ],
    [ "aiColor3D", "structai_color3_d.html", "structai_color3_d" ],
    [ "aiColor4D", "structai_color4_d.html", "structai_color4_d" ],
    [ "aiExportDataBlob", "structai_export_data_blob.html", "structai_export_data_blob" ],
    [ "aiExportFormatDesc", "structai_export_format_desc.html", "structai_export_format_desc" ],
    [ "aiFace", "structai_face.html", "structai_face" ],
    [ "aiFile", "structai_file.html", "structai_file" ],
    [ "aiFileIO", "structai_file_i_o.html", "structai_file_i_o" ],
    [ "aiImporterDesc", "structai_importer_desc.html", "structai_importer_desc" ],
    [ "aiLight", "structai_light.html", "structai_light" ],
    [ "aiLogStream", "structai_log_stream.html", "structai_log_stream" ],
    [ "aiMaterial", "structai_material.html", "structai_material" ],
    [ "aiMatrix3x3", "structai_matrix3x3.html", "structai_matrix3x3" ],
    [ "aiMatrix4x4", "structai_matrix4x4.html", "structai_matrix4x4" ],
    [ "aiMemoryInfo", "structai_memory_info.html", "structai_memory_info" ],
    [ "aiMesh", "structai_mesh.html", "structai_mesh" ],
    [ "aiMeshAnim", "structai_mesh_anim.html", "structai_mesh_anim" ],
    [ "aiMeshKey", "structai_mesh_key.html", "structai_mesh_key" ],
    [ "aiMeshMorphAnim", "structai_mesh_morph_anim.html", "structai_mesh_morph_anim" ],
    [ "aiMeshMorphKey", "structai_mesh_morph_key.html", "structai_mesh_morph_key" ],
    [ "aiMetadata", "structai_metadata.html", "structai_metadata" ],
    [ "aiMetadataEntry", "structai_metadata_entry.html", "structai_metadata_entry" ],
    [ "aiNode", "structai_node.html", "structai_node" ],
    [ "aiNodeAnim", "structai_node_anim.html", "structai_node_anim" ],
    [ "aiPlane", "structai_plane.html", "structai_plane" ],
    [ "aiPropertyStore", "structai_property_store.html", "structai_property_store" ],
    [ "aiQuaternion", "structai_quaternion.html", "structai_quaternion" ],
    [ "aiQuatKey", "structai_quat_key.html", "structai_quat_key" ],
    [ "aiRay", "structai_ray.html", "structai_ray" ],
    [ "aiScene", "structai_scene.html", "structai_scene" ],
    [ "aiString", "structai_string.html", "structai_string" ],
    [ "aiTexel", "structai_texel.html", "structai_texel" ],
    [ "aiTexture", "structai_texture.html", "structai_texture" ],
    [ "aiUVTransform", "structai_u_v_transform.html", "structai_u_v_transform" ],
    [ "aiVector2D", "structai_vector2_d.html", "structai_vector2_d" ],
    [ "aiVector3D", "structai_vector3_d.html", "structai_vector3_d" ],
    [ "aiVectorKey", "structai_vector_key.html", "structai_vector_key" ],
    [ "aiVertexWeight", "structai_vertex_weight.html", "structai_vertex_weight" ],
    [ "DeadlyImportError", "class_deadly_import_error.html", "class_deadly_import_error" ],
    [ "ExceptionSwallower", "struct_exception_swallower.html", "struct_exception_swallower" ],
    [ "ExceptionSwallower< aiReturn >", "struct_exception_swallower_3_01ai_return_01_4.html", "struct_exception_swallower_3_01ai_return_01_4" ],
    [ "ExceptionSwallower< T * >", "struct_exception_swallower_3_01_t_01_5_01_4.html", "struct_exception_swallower_3_01_t_01_5_01_4" ],
    [ "ExceptionSwallower< void >", "struct_exception_swallower_3_01void_01_4.html", "struct_exception_swallower_3_01void_01_4" ],
    [ "FaceWithSmoothingGroup", "struct_face_with_smoothing_group.html", "struct_face_with_smoothing_group" ],
    [ "MeshWithSmoothingGroups", "struct_mesh_with_smoothing_groups.html", "struct_mesh_with_smoothing_groups" ]
];