var hierarchy =
[
    [ "_IEEEDouble", "union___i_e_e_e_double.html", null ],
    [ "_IEEESingle", "union___i_e_e_e_single.html", null ],
    [ "Assimp::ByteSwap::_swapper< T, 2 >", "struct_assimp_1_1_byte_swap_1_1__swapper_3_01_t_00_012_01_4.html", null ],
    [ "Assimp::ByteSwap::_swapper< T, 4 >", "struct_assimp_1_1_byte_swap_1_1__swapper_3_01_t_00_014_01_4.html", null ],
    [ "Assimp::ByteSwap::_swapper< T, 8 >", "struct_assimp_1_1_byte_swap_1_1__swapper_3_01_t_00_018_01_4.html", null ],
    [ "aiAABB", "structai_a_a_b_b.html", null ],
    [ "aiAnimation", "structai_animation.html", null ],
    [ "aiAnimMesh", "structai_anim_mesh.html", null ],
    [ "aiBone", "structai_bone.html", null ],
    [ "aiCamera", "structai_camera.html", null ],
    [ "aiColor3D", "structai_color3_d.html", null ],
    [ "aiColor4D", "structai_color4_d.html", null ],
    [ "aiExportDataBlob", "structai_export_data_blob.html", null ],
    [ "aiExportFormatDesc", "structai_export_format_desc.html", null ],
    [ "aiFace", "structai_face.html", null ],
    [ "aiFile", "structai_file.html", null ],
    [ "aiFileIO", "structai_file_i_o.html", null ],
    [ "aiImporterDesc", "structai_importer_desc.html", null ],
    [ "aiLight", "structai_light.html", null ],
    [ "aiLogStream", "structai_log_stream.html", null ],
    [ "aiMaterial", "structai_material.html", null ],
    [ "aiMatrix3x3", "structai_matrix3x3.html", null ],
    [ "aiMatrix4x4", "structai_matrix4x4.html", null ],
    [ "aiMemoryInfo", "structai_memory_info.html", null ],
    [ "aiMesh", "structai_mesh.html", null ],
    [ "aiMeshAnim", "structai_mesh_anim.html", null ],
    [ "aiMeshKey", "structai_mesh_key.html", null ],
    [ "aiMeshMorphAnim", "structai_mesh_morph_anim.html", null ],
    [ "aiMeshMorphKey", "structai_mesh_morph_key.html", null ],
    [ "aiMetadata", "structai_metadata.html", null ],
    [ "aiMetadataEntry", "structai_metadata_entry.html", null ],
    [ "aiNode", "structai_node.html", null ],
    [ "aiNodeAnim", "structai_node_anim.html", null ],
    [ "aiPlane", "structai_plane.html", null ],
    [ "aiPropertyStore", "structai_property_store.html", null ],
    [ "aiQuaternion", "structai_quaternion.html", null ],
    [ "aiQuatKey", "structai_quat_key.html", null ],
    [ "aiRay", "structai_ray.html", null ],
    [ "aiScene", "structai_scene.html", null ],
    [ "aiString", "structai_string.html", null ],
    [ "aiTexel", "structai_texel.html", null ],
    [ "aiTexture", "structai_texture.html", null ],
    [ "aiUVTransform", "structai_u_v_transform.html", null ],
    [ "aiVector2D", "structai_vector2_d.html", null ],
    [ "aiVector3D", "structai_vector3_d.html", null ],
    [ "aiVectorKey", "structai_vector_key.html", null ],
    [ "aiVertexWeight", "structai_vertex_weight.html", null ],
    [ "AllocateFromAssimpHeap", null, [
      [ "Assimp::IOStream", "class_assimp_1_1_i_o_stream.html", [
        [ "Assimp::BlobIOStream", "class_assimp_1_1_blob_i_o_stream.html", null ],
        [ "Assimp::DefaultIOStream", "class_assimp_1_1_default_i_o_stream.html", null ],
        [ "Assimp::MemoryIOStream", "class_assimp_1_1_memory_i_o_stream.html", null ]
      ] ],
      [ "Assimp::IOSystem", "class_assimp_1_1_i_o_system.html", [
        [ "Assimp::BlobIOSystem", "class_assimp_1_1_blob_i_o_system.html", null ],
        [ "Assimp::DefaultIOSystem", "class_assimp_1_1_default_i_o_system.html", null ],
        [ "Assimp::MemoryIOSystem", "class_assimp_1_1_memory_i_o_system.html", null ],
        [ "Assimp::ZipArchiveIOSystem", "class_assimp_1_1_zip_archive_i_o_system.html", null ]
      ] ],
      [ "Assimp::Logger", "class_assimp_1_1_logger.html", [
        [ "Assimp::DefaultLogger", "class_assimp_1_1_default_logger.html", null ],
        [ "Assimp::NullLogger", "class_assimp_1_1_null_logger.html", null ]
      ] ],
      [ "Assimp::LogStream", "class_assimp_1_1_log_stream.html", null ],
      [ "Assimp::ProgressHandler", "class_assimp_1_1_progress_handler.html", null ]
    ] ],
    [ "Assimp::AttachmentInfo", "struct_assimp_1_1_attachment_info.html", null ],
    [ "Assimp::BaseImporter", "class_assimp_1_1_base_importer.html", null ],
    [ "Assimp::Formatter::basic_formatter< T, CharTraits, Allocator >", "class_assimp_1_1_formatter_1_1basic__formatter.html", null ],
    [ "Assimp::Bitmap", "class_assimp_1_1_bitmap.html", null ],
    [ "Assimp::ByteSwap", "class_assimp_1_1_byte_swap.html", null ],
    [ "Assimp::Intern::ByteSwapper< T, doit >", "struct_assimp_1_1_intern_1_1_byte_swapper.html", null ],
    [ "Assimp::Intern::ByteSwapper< T, false >", "struct_assimp_1_1_intern_1_1_byte_swapper_3_01_t_00_01false_01_4.html", null ],
    [ "Assimp::CommentRemover", "class_assimp_1_1_comment_remover.html", null ],
    [ "Assimp::Bitmap::DIB", "struct_assimp_1_1_bitmap_1_1_d_i_b.html", null ],
    [ "Assimp::Intern::divides< T0, T1, TRES >", "struct_assimp_1_1_intern_1_1divides.html", null ],
    [ "Assimp::SGSpatialSort::Entry", "struct_assimp_1_1_s_g_spatial_sort_1_1_entry.html", null ],
    [ "Assimp::SpatialSort::Entry", "struct_assimp_1_1_spatial_sort_1_1_entry.html", null ],
    [ "ExceptionSwallower< T >", "struct_exception_swallower.html", null ],
    [ "ExceptionSwallower< aiReturn >", "struct_exception_swallower_3_01ai_return_01_4.html", null ],
    [ "ExceptionSwallower< T * >", "struct_exception_swallower_3_01_t_01_5_01_4.html", null ],
    [ "ExceptionSwallower< void >", "struct_exception_swallower_3_01void_01_4.html", null ],
    [ "Assimp::Exporter", "class_assimp_1_1_exporter.html", null ],
    [ "Assimp::Exporter::ExportFormatEntry", "struct_assimp_1_1_exporter_1_1_export_format_entry.html", null ],
    [ "Assimp::ExportProperties", "class_assimp_1_1_export_properties.html", null ],
    [ "Assimp::SkeletonMeshBuilder::Face", "struct_assimp_1_1_skeleton_mesh_builder_1_1_face.html", null ],
    [ "FaceWithSmoothingGroup", "struct_face_with_smoothing_group.html", null ],
    [ "Assimp::Intern::Getter< SwapEndianess, T, RuntimeSwitch >", "struct_assimp_1_1_intern_1_1_getter.html", null ],
    [ "Assimp::Intern::Getter< SwapEndianess, T, false >", "struct_assimp_1_1_intern_1_1_getter_3_01_swap_endianess_00_01_t_00_01false_01_4.html", null ],
    [ "Assimp::Bitmap::Header", "struct_assimp_1_1_bitmap_1_1_header.html", null ],
    [ "IFileReadCallBack", null, [
      [ "Assimp::CIrrXML_IOStreamReader", "class_assimp_1_1_c_irr_x_m_l___i_o_stream_reader.html", null ]
    ] ],
    [ "Assimp::Importer", "class_assimp_1_1_importer.html", null ],
    [ "Assimp::IOStreamBuffer< T >", "class_assimp_1_1_i_o_stream_buffer.html", null ],
    [ "Assimp::LineSplitter", "class_assimp_1_1_line_splitter.html", null ],
    [ "Assimp::LogFunctions< TDeriving >", "class_assimp_1_1_log_functions.html", null ],
    [ "MeshWithSmoothingGroups< T >", "struct_mesh_with_smoothing_groups.html", null ],
    [ "Assimp::Intern::minus< T0, T1, TRES >", "struct_assimp_1_1_intern_1_1minus.html", null ],
    [ "Assimp::Intern::multiplies< T0, T1, TRES >", "struct_assimp_1_1_intern_1_1multiplies.html", null ],
    [ "Assimp::NodeAttachmentInfo", "struct_assimp_1_1_node_attachment_info.html", null ],
    [ "pair", null, [
      [ "Assimp::BoneWithHash", "struct_assimp_1_1_bone_with_hash.html", null ]
    ] ],
    [ "Assimp::Intern::plus< T0, T1, TRES >", "struct_assimp_1_1_intern_1_1plus.html", null ],
    [ "Assimp::Profiling::Profiler", "class_assimp_1_1_profiling_1_1_profiler.html", null ],
    [ "Assimp::SceneCombiner", "class_assimp_1_1_scene_combiner.html", null ],
    [ "Assimp::SceneHelper", "struct_assimp_1_1_scene_helper.html", null ],
    [ "Assimp::SGSpatialSort", "class_assimp_1_1_s_g_spatial_sort.html", null ],
    [ "Assimp::SkeletonMeshBuilder", "class_assimp_1_1_skeleton_mesh_builder.html", null ],
    [ "Assimp::SpatialSort", "class_assimp_1_1_spatial_sort.html", null ],
    [ "Assimp::StandardShapes", "class_assimp_1_1_standard_shapes.html", null ],
    [ "Assimp::StreamReader< SwapEndianess, RuntimeSwitch >", "class_assimp_1_1_stream_reader.html", null ],
    [ "Assimp::StreamWriter< SwapEndianess, RuntimeSwitch >", "class_assimp_1_1_stream_writer.html", null ],
    [ "Assimp::Subdivider", "class_assimp_1_1_subdivider.html", null ],
    [ "Assimp::Vertex", "class_assimp_1_1_vertex.html", null ],
    [ "runtime_error", null, [
      [ "DeadlyImportError", "class_deadly_import_error.html", null ]
    ] ]
];